### PR TITLE
Turn off rendering inner HTML by default

### PR DESCRIPTION
**Pull request by ntietz**
As a side effect of fixing ryandrewjohnson/react-localize-redux#11, inner HTML is rendered by default. To me, this seems problematic for two reasons:

- It's unexpected; if I am passing a string in to be translated, I expect a string back. There are some instances where it may make sense to pass HTML through without rendering (for example, inside multi-lingual code samples).
- It's a security risk; if user-generated content is ever passed through `translate`, it could cause injection of HTML elements and allow an XSS attack. An example of a use case for translating user-generated content is if you have crowd-sourced translations (either of general site content, or of user-submitted content).

I suggest turning this off by default. This PR includes:

- Tests of my suggested behavior (off by default, can explicitly request inner rendering)
- Code to make the tests pass

### CODE REVIEW

**Comment by ryandrewjohnson** [comment]
Thanks for sending this over. I like the idea of having the additional parameter to control the rendering of HTML, but I'm not in agreement with having it set to false by default. 

If you're cool making these couple updates to the PR then I'd be good to merge it.

1. Change the additional argument to be an options object instead of a single boolean value. This will allow for additional options to be added in the future if needed without introducing breaking changes. Something like this...

```javascript
const defaultOptions = {
   renderInnerHtml: true
};

return (value, data, options) => {
   const translateOptions = { ...defaultOptions, ...options };
   ...
}
```

2. Also add this `options` object so it can be added to `localize` as an additional argument as well. This way it will stay in sync with getTranslate.

3. Change the default value of `renderInnerHtml` to true instead of false. Here is my reasoning for that:
* Although there could be potential security risks if you're loading translation content from third party sources, I believe a lot of people will be using their own data that they control. That being the case I think it makes more sense to have the user who is loading third-party (un-trusted) content to be the one to set `renderInnerHtml` flag to false to turn off that feature.
* I have been giving some thought on enhancing the HTML detection to also include some checks for malicious scripts as well. In this case if one of these malicious scripts was detected the `renderInnerHtml` would be forced to false. If you have any interest in helping out with this let me know. It wouldn't be to catch all script injection scenarios, as that would be nearly impossible, but at least it could weed out the most obvious ones.

Let me know what you think.

**Comment by ntietz** [comment]
I updated to use an options object instead. I went the route of putting it in state since that seemed to be the easiest way to get it consistent across the board (adding an options argument to pass into `translate` seems like a bad developer experience since then the developer would have to manage where that options object lives).

Could you check that the `localize` component works as you would expect? I honestly did not test it, although I expect it to work since the selector passes tests and the state should be the same here as it is in those tests. The tests just cover the pure functions elsewhere.

I did change `renderInnerHtml` to default to true, but I strongly disagree with the reasons for doing so. In my mind, the only reason to keep it `true` is because changing the default would be a surprise update that would break some people's code. I would suggest changing it to `false` when you bump the major version in the future, for these reasons:

-  It's true that most people use data under their control, however -- React already makes it so you have to consciously think about setting inner html, and it's off by default. Having your lib have it off by default as well fits the principle of least surprise.
- HTML detection checking for malicious scripts is a bandaid over a bullet hole, in my opinion. It will give the appearance of security but you're playing whack-a-mole with attackers. Not good, when you can solve the problem by having the default be the secure option.
- In general, I think the default should be for security, not for convenience. If you *want* this option on, it's not hard to add a setting to enable it one time. But if you don't *need* this option on, then you probably won't think about it -- and suddenly most users are living in a less secure world, because the default was less secure.

Food for thought. As it stands, I think that the changes fit your criteria. Let me know if you need anything else in this PR, and please consider changing your stance on the default, when you have the option to change it (when other breaking changes are made would be a good time).

**Comment by ryandrewjohnson** [comment]
Thanks for the update. I'm just reviewing them now, and working on tweaking things on my end, and will push when I'm done.

In regards to setting the `renderInnerHtml` to false by default you raise some good points. Especially the point you made where it makes sense to follow React's settings, which is to have this option off by default. I'm still trying to decide whether to change this now, and introduce the breaking change, or wait for some other breaking changes like you mentioned.

**Comment by ntietz** [comment]
Awesome. If you want me to do any of the tweaks, let me know. I know the burden on maintainers can be high so if there's anything you prefer me to handle, feel free to throw it back my way.

**Comment by ryandrewjohnson** [comment]
Thanks for the offer I will definitely keep that in mind. In terms of the tweaks I've been thinking I may make a more significant change in how things work. Currently we have the `setLanguages` action that really only gets called once when bootstrapping your application. Now we're adding this `setOptions` action, which again would primarily only be called once, and usually when the app bootstraps.

I'm thinking instead of dispatching both these actions separately it makes more sense to maybe create a `init` action that handles both setting the `languages` and the `options`. So it would look something like this...

```javascript
const defaultOptions = {
    renderInnerHtml: true,
};
export const init(languages, options = defaultOptions) {}

// with default options
store.dispatch(init(['en', 'fr']);

// override default language
store.dispatch(init(['en', 'fr'], { defaultLanguage:  'fr' });

// override renderInnerHtml
store.dispatch(init(['en', 'fr'], { renderInnerHtml:  false });
```

Also to avoid breaking changes I would keep the existing `setLanguages` action for now, and mark it as deprecated, and log out some sort of warning letting the user know this will be changing in next major version.

What do you think?

**Comment by ntietz** [comment]
I like that a lot. I'm in favor of making that change. I have the time to
contribute to that change this weekend if you'd like me to do it.

**Comment by ryandrewjohnson** [comment]
I already have started, and I'm hoping to push it out tonight if possible. It would be great if you could review it though if you're up for it?

**Comment by ntietz** [comment]
For sure! I can probably do that review on Thursday, otherwise it will be
on the weekend. I will make time for it.

**Comment by ryandrewjohnson** [comment]
That's great!

Another feature I've been thinking of adding is some sort of redux middleware to allow for translation data transformations. The use case being users who have existing data, or maybe some sort of third party translation data that isn't in the required format could then use the middleware to transform their data into the format required for react-localize-redux.

Haven't flushed out functionality, but middleware would allow the user to provide some sort of transformation function that would follow some sort of pre-determined interface. The transformation function would be written by user, and transform the user's data format to the required format for react-localize-redux. The middleware would then  listen for both `addTranslation` and `addTranslationForLanguage` and apply the transformation to the data coming in.

If this is something you'd be interested in helping out on let me know.

**Comment by ryandrewjohnson** [comment]
@ntietz I'm going to close this PR as we've diverted quite a bit from the original issue. I have created a new [feature branch](https://github.com/ryandrewjohnson/react-localize-redux/tree/feature/initialize-options) based off of your changes.  

I have completed all the logic and I'm just working on updating the documentation, which I should be able to complete by tomorrow. When I'm done I'll create a new PR and have you review.

**Pull request closed without merging**
