### PR TITLE
Support ImmutableJS state

### PR DESCRIPTION
**Pull request by jamiedust**
This solves the issue of using Immutable JS with the localize HOC here #49

### CODE REVIEW

**Comment by ryandrewjohnson** [comment]
I'm not a big fan of adding ImmutableJS as a required dependency for the entire library, when it's only a requirement for those using ImmutableJS. I need to take a closer look a this as the only way I see this working is:

1. Figure out a way to make it work without including the dependency.
2. Figure out a way to make this an opt in type feature/dependency.

If you have any ideas please let me know as I have yet to work with immutablejs myself.

**Comment by ryandrewjohnson** [comment]
Ok I think I have an idea...

I can add a third param to the `Localize` function that takes a function that allows the user to create their own `getStateSlice` logic. This `getStateSlice` function would have a type like so `(state) => state`.

So in your case you'd do something like this.

```javascript
const getStateSlice = (state) => {
   return state.toJS()['locale'];
};

// then you'd call localize like so 
 localize(MockPageComponent, 'locale', getStateSlice);

// from localize I would handle it like so 
const scopedState = getStateSlice !== undefined
    ? getStateSlice(state)
    : slice && state[slice]) || state;
```

This way things remain backwards compatible, and there is no dependency on immutablejs. This could also allow for other state libraries to alter this functionality if necessary. 

Let me know what you think, as I could have this change out pretty quick.

**Comment by ryandrewjohnson** [comment]
@jamiedust I just created a new PR #58 that implements the fix I described above. Can you pull the branch and see if it works on your end? I ran the unit test with ImmutableJS and it passes, but I would like to run in an actual project using immutablejs before merging.

**Comment by jamiedust** [comment]
Hi, I understand you not wanting to include Immutable. Ive just tried your solution and it works great, and of course its much more flexible.

**Comment by ryandrewjohnson** [comment]
Ok thanks for taking a look. I'll close this PR, and merge the other one tonight, and draft a new release.

**Pull request closed without merging**
