### PR TITLE
SSR support with initialize prop added to LocalizeProvider

### PR DESCRIPTION
**Pull request by ramyma**
- Added initialize prop to LocalizeProvider to make it possible to initialize the context with SSR

### CODE REVIEW

**Comment by ramyma** [comment]
To solve https://github.com/ryandrewjohnson/react-localize-redux/issues/125

**Comment by ryandrewjohnson** [comment]
Thanks for sending this over. This is on the right track of what I was thinking, but I ended up flushing this out a bit differently. In addition included a unit test, and added the required types. 

Please have a look at #127 and let me know what you think. It'd be great if you could verify in a real server rendered app.

**Comment by ramyma** [comment]
Yeah, I tried to dig into the code and figure out the types, I'm sure you're better acquainted with the code base than I am.

Looks like it'll do the trick, I'll give it a try and let you know how it goes.

Thanks for taking the time to do this.

**Comment by ryandrewjohnson** [comment]
Closing as work is now captured in #127

**Pull request closed without merging**
