### PR TITLE
Feature/initialize options

### PR DESCRIPTION
**Pull request by ryandrewjohnson**
New features based on discussions in issue #18 with contributions from @ntietz
* add new `initialize` action creator
* add new `options` argument to `translate` function
* deprecate `setLanguges` action creator
* optimize `customeEqualSelector`
* update documentation

### CODE REVIEW

**Comment by ryandrewjohnson** [comment]
@ntietz I've sent you an invite to be a collaborator on the project. Once you have accepted I can add you as a reviewer on the PR.

**Comment by ryandrewjohnson** [comment]
@ntietz have you had a chance to review this at all?

**Comment by ntietz** [comment]
I have not. It is on my todo list for tomorrow 👍

**Comment by ryandrewjohnson** [comment]
@ntietz thanks for the help on this one. 🍻

**Comment by ntietz** [comment]
Likewise, thanks for moving quickly on it! Maintenance isn't easy, so I appreciate it.

If there are some other issues you'd like some help on, feel free to @ me on them.

**Pull request merged**
