### PR TITLE
Allow React components as dynamic data arguments.

### PR DESCRIPTION
**Pull request by thchia**
I'm just going to throw this out here as a suggestion for when the time is right. Maybe in the meantime other users can contribute.

Outline of the approach I have taken.

### Before
`templater()` would return a string with all the dynamic content filled in:
```javascript

const translation = 'Hello ${ name }'
const data = { name: 'Google' }

templater(translation, data) // 'Hello Google'

```
`getLocalizedElement` would check if the result of `templater()` has any HTML tags in it:
```javascript
const getLocalizedElement = (...args) => {

  ...

  const translatedValues = templater(translations, data)

  return renderInnerHtml && hasHtmlTags(translatedValues)
  ?  React.createElement('span', { dangerouslySetInnerHTML: { __html: translatedValues } })
  : translatedValues

}
```

### After
`templater()` returns a string if the dynamic content does not contain any values satisfying `React.isValidElement()`. Otherwise, it returns an array of string/React components:
```javascript
const translation = 'Hello ${name}'
const data = { name: 'Google' }

templater(translation, data) // 'Hello Google'

...

const translation = 'Hello ${name}'
const Component = () => <strong>Google</strong>
const data = { name: <Component /> }

templater(translation, data) // ['Hello', <strong>Google</strong> ]
```
`getLocalizedElement` checks if the result of `templater` is a string or not. If it is, it does the same as before. If it is not (i.e. we are passing React components as dynamic content, and it is an array), first check that no string element in the array satisfies `hasHtmlTags()` (see below). If that check passes, spread the array into `React.createElement`:
```javascript
// Pseudocode

const getLocalizedElement = (...args) => {
  
  ...
  
  const translatedValues = templater(translations, data)

  if (typeof translatedValues === 'string') {
    // return same as before
  }

  // check for hasHtmlTags()

  return React.createElement('span', null, ...translatedValues)
}
```

### Known issues
* HTML in translations: This approach does not support having HTML in the translation. The reason is that the templater will split the stringified HTML into `[ '<span>', <strong>Google</strong>, '</span>' ]` and I'm not sure how to re-form this into HTML. Using `dangerouslySetInnerHTML` will lose the `<strong>Google</strong>` (because it is *not* a string), but is the current way of parsing the string HTML.

* React Native: Any translations with React components in data are returned as `React.createElement('span', ...)`. This won't work in RN. I'm less familiar with RN so wonder if replacing `span` with `Fragment` would work.

### CODE REVIEW

**Comment by ryandrewjohnson** [comment]
@thchia at first glance this looks really good - thanks for putting it together. I would prefer to hold this back though until after v3 launches, as it is a larger enhancement that I want to test/discuss further before including.

**Comment by thchia** [comment]
@ryandrewjohnson yeah no worries, this is just to get the ball rolling and hopefully invite some collaboration 🙂

**Comment by ryandrewjohnson** [comment]
I'm just now finally getting a chance to look at this. I'm hoping to have some feedback to you in the next couple changes. Just wanted to let you know it's not been forgotten 👍

**Comment by ryandrewjohnson** [comment]
@thchia there are a few tweaks I'd like to push, but I'm just having trouble getting the time to work on them. I wanted to keep you in the loop though.

**Comment by ryandrewjohnson** [comment]
@thchia I would like to get this feature in before it gets more behind master. We can iterate on it over time, but I think what you have here is good to go as is. Before we merge though can you rebase with master to get things back up to date? 

Also could you update the docs with this new feature? I think it warrants its own heading in the `Guides` section. Once that's ready to go we can get this all merged in and published.

**Comment by thchia** [comment]
@ryandrewjohnson How are you with me re-creating this PR from the current master? I seem to have messed up some of the upstream merges (there should not be changes in the lock files for example). The only code changes are in `utils` and the test files so it's no sweat to create a clean PR.

**Comment by ryandrewjohnson** [comment]
@thchia feel free to open a new PR if that is easier.

**Comment by thchia** [comment]
Closed in favour of #100

**Pull request closed without merging**
