### PR TITLE
Update state render

### PR DESCRIPTION
**Pull request by thchia**
In response to #84.

### Summary
React warnings were emitted about an invalid state update. I think it is because there was a state update somewhere in the tree caused during the `render` method of `<Translate />`. `<Translate />` called `addDefaultTranslation()` during the render phase and I think this was the source of the problem.

My suggested solution is to remove the call to `addDefaultTranslation()` from the render phase of Translate, and call it once on mount, and subsequently every time the `id` prop changes (#79).

### Before
1. Translate mounts with state:
```javascript
state = { hasAddedDefaultTranslation: false, lastKnownId: '' }
```
2. `static getDerivedStateFromProps()` runs to determine when the `id` prop changes. Whenever this prop changes, it resets the `state.hasAddedDefaultTranslation` flag.
3. `render()` is called and subsequently calls `addDefaultTranslation()`, which will decide what to do based on the current state.

### After
1. `componentDidMount()` calls `addDefaultTranslation()`.
2. `componentDidUpdate()` calls `addDefaultTranslation()` **if** the `id` prop has changed.
3. No calls to `addDefaultTranslation()` in the render phase.

### Moving the Consumer
Previously, the render phase was called with the `LocalizeContext.Consumer` which provided the `context` object needed in `addDefaultTranslation`. Since this is not happening anymore, I have had to move the Context Consumer one level up, and pass `context` down as a Prop to `Translate`. This means the public-facing `Translate` component is no longer the original one, but the original one wrapped in `LocalizeContext.Consumer`. This way the entire `WrappedTranslate` (i.e. the original `Translate`) has access to `context` and we can successfully call `addDefaultTranslation` at any point in the life cycle. I'm not sure if this affects performance?

I don't know how to write an effective test for this... The particular error seems to be either not triggered or suppressed in some way in the current tests. However, the error is reproducible in the demo project, and it can be verified as gone with this change by building the demo project with the parent directory as the `react-localize-redux` dependency.

### CODE REVIEW

**Comment by ryandrewjohnson** [comment]
Thanks for all the detail it really helps. In terms of performance, I don't foresee any issues with the wrapper component. 

A couple of small things:

* I think the type definitions in `index.d.ts` and `index.flow.js` need to be updated for `Translate` to reflect this change. Let me know if you need help with that.
* I wouldn't even bother exporting `WrappedTranslate` unless it's needed for testing purposes.
* Now that you've removed `getDerivedStateFromProps` from `Translate` I think we can bump down the `peerDependency` in `package.json` back to `react: 16.0.0`.

So if the issue can't be captured in a test I'm guessing you've confirmed this fix solves the issue in the demo as you mentioned? I just want to confirm.

**Comment by thchia** [comment]
@ryandrewjohnson latest update:

* I'm not sure if the definitions do need to be updated, since the new `Translate` component still accepts the same props and renders the same children as before. The only difference is that `WrappedTranslate` has an additional `context` prop, but since this component is private, I don't think any existing definitions need changing.

* I've removed the export of `WrappedTranslate` and changed the `peerDependency` as suggested.

* I have confirmed that the issue no longer presents itself via the demo project. Note that I tested this by setting the `react-localize-redux` dependency as my _local_ copy in the demo, so even after this PR, the demo should continue to show the error, until it can point to a fixed version of `react-localize-redux`.

**Comment by ryandrewjohnson** [comment]
I think the flow type def is fine, but the typescript def in `index.d.ts` should probably be updated as it's no longer exporting a class. 

Current:
```
export class Translate extends ReactComponent<TranslateProps> {}
```

It should now probably export a function similar to the `withLocalize` definition.

**Comment by thchia** [comment]
Good point. I typed it as a `React.SFC` since it is technically now a stateless functional component.

**Comment by ryandrewjohnson** [comment]
Great work on this one! I've merged it in for now, but will publish tomorrow when I have some time. Don't want to rush it at the end of the night as that's usually when I end up breaking something 😬

**Pull request merged**
